acquiring:
  qiwi:
      # Секретный ключ P2P API
      token: 000
      
      # Коэффициент мультипликации
      multiplication: 1
      
      # Команда, которая срабатывает при прохождении оплаты
      # Например /money give %player% %amount%
      # %player% - игрок, который задонатил, %amount% - число, полученное при умножении задоначенной суммы на коэффициент мультипликации
      command: "ancapdonates:bal give %player% %amount%"
      
      # Qiwi перенаправит сюда после оплаты
      site: "ancapmine.ru"
      
      # Телефон, вводить в международной форме без "+", вот так: 79987894554
      phone: "79326062982"
      
      # Электронная почта, на которую зарегистрирован ваш QIWI кошелёк
      email: "govno.govv@mail.ru"
      
      # Срок, через который счёт истечёт, в минутах. Рекомендуется не менять
      bill-expiration-time: 60
      
      # Валюта для приёма платежей
      currency: "RUB"
      
      # Код темы для формы оплаты, не обязательно
      # theme-code: 