acquiring:
  qiwi:
    # Секретный ключ P2P API
    token: 000
    
    # Qiwi перенаправит сюда после оплаты
    site: "ancapmine.ru"
    
    # Телефон, вводить в международной форме без "+", вот так: 79987894554
    phone: "79326062982"
    
    # Электронная почта, на которую зарегистрирован ваш QIWI кошелёк
    email: "govno.govv@mail.ru"
    
    # Срок, через который счёт истечёт, в минутах. Рекомендуется не менять
    bill-expiration-time: 60
    
    # Валюта для приёма платежей
    currency: "RUB"
    
payments:
  
  # Коэффициент мультипликации
  multiplication: 1
  # Команда, которая срабатывает при прохождении оплаты
  # Например - /money give %PLAYER% %AMOUNT%
  # %player% - игрок, который задонатил, %AMOUNT% - число, полученное при умножении задоначенной суммы на коэффициент мультипликации
  command: "reward %PLAYER% %AMOUNT%"

donates:
  vip:
    price: 100
    command: "kill %PLAYER%"
  premium:
    price: 250
    command: "lp user %PLAYER% parent addtemp premium 30d"
  