name: QiwiPay
version: '${project.version}'
main: ru.ancap.pay.plugin.AncapPay
authors: [PukPukov, moskovroma, Riku]

depend: [Artifex]

commands:
  donate:
    aliases: [pay]
  promo-code:
  ancap-pay:
  wallet:
  buy:
  reward: